---
- name: service module demo
  hosts: all
  become: true
  vars: 
    service_on_boot:
      - "chrony"
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
      
    - name: enable services on boot
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      when: "item in services"
      with_items: "{{ service_on_boot }}"
