---
- name: Reboot Server
  hosts: centos
  become: true
  tasks: 
    - name: Reboot Server
      ansible.builtin.reboot:
        msg: 'Reboot initied by Ansible'
        test_command: 'whoami'
        pre_reboot_delay: 5
        post_reboot_delay: 5
